services:
  app:
    build: .
    ports:
      - '8000:8000'
    depends_on:
      - db
      - rabbitmq
  celery_worker:
    build: .
    command: poetry run celery -A worker.celery worker --loglevel=info
    depends_on:
      - rabbitmq
      - cache
  db:
    image: postgres:17.5
    restart: always
    shm_size: 128mb
    ports:
      - '${DB_TEST_PORT:-5433}:5432'
    env_file:
      - ./.local.env

  cache:
    image: redis:8.2-alpine
    restart: always
    ports:
      - '6379:6379'
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
