"""remove category

Revision ID: 8f4469bded16
Revises: 3de91cdd7c2e
Create Date: 2025-09-03 11:42:26.002627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f4469bded16'
down_revision: Union[str, Sequence[str], None] = '3de91cdd7c2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Categories')
    op.drop_column('Tasks', 'category_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Tasks', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_table('Categories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('Categories_pkey'))
    )
    # ### end Alembic commands ###
